name: PouchDB Docs

on:
  push:
    paths:
      - '.github/ISSUE_TEMPLATE/'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'CONTRIBUTING.md'
      - 'DISCLAIMER'
      - 'LICENSE'
      - 'NOTICE'
      - 'README.md'
      - 'TESTING.md'
      - 'docs/**'

  pull_request:
    branches: [master]
    paths:
      - '.github/ISSUE_TEMPLATE/'
      - '.github/PULL_REQUEST_TEMPLATE.md'
      - 'CONTRIBUTING.md'
      - 'DISCLAIMER'
      - 'LICENSE'
      - 'NOTICE'
      - 'README.md'
      - 'TESTING.md'
      - 'docs/**'

jobs:

  test-docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: ./.github/actions/install-node-package
        with:
          node-version: 24
      - run: BUILD=1 npm run build-site
