# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Set up CouchDB
      uses: "cobot/couchdb-action@master"
      with:
        couchdb version: '2.3.1'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm run eslint
    - run: AUTO_COMPACTION=true npm test
    - run: TYPE=mapreduce npm test
    - run: COUCH_HOST=http://127.0.0.1:5984 TYPE=find PLUGINS=pouchdb-find CLIENT=node SERVER=couchdb-master npm test
    - run: PERF=1 npm test
    - run: npm run test-unit
    - run: npm run test-component
    - run: npm run test-fuzzy
    - run: SERVER=pouchdb-server POUCHDB_SERVER_FLAGS=--in-memory PLUGINS=pouchdb-find COVERAGE=1 npm run report-coverage
    - run: npm run verify-build
    