# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      options: --network-alias testHost

    env:
      SELENIUM_HUB_HOST: hub
      TEST_HOST: testHost

    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node: [12, 14, 16]
        couchdb: ['2.3', '3.1']
        command: [
          # 'CLIENT=selenium:firefox ADAPTER=idb POUCHDB_SRC="../../packages/node_modules/pouchdb/dist/pouchdb.min.js" npm test',
          # 'CLIENT=selenium:firefox ADAPTER=indexeddb POUCHDB_SRC="../../packages/node_modules/pouchdb/dist/pouchdb.min.js" npm test',
          # 'TYPE=mapreduce CLIENT=selenium:firefox ADAPTER=indexeddb npm test',
          # 'CLIENT=selenium:firefox npm run test-webpack',
          # 'AUTO_COMPACTION=true npm test',
          # 'TYPE=mapreduce npm test',
          # 'COUCH_HOST=http://127.0.0.1:5984 TYPE=find PLUGINS=pouchdb-find CLIENT=node SERVER=couchdb-master npm test',
          # 'PERF=1 npm test',
          # 'npm run test-unit',
          # 'npm run test-component',
          # 'npm run test-fuzzy',
          # 'SERVER=pouchdb-server POUCHDB_SERVER_FLAGS=--in-memory PLUGINS=pouchdb-find COVERAGE=1 npm run report-coverage',
          'npm run verify-build'
        ]

    steps:
    - uses: actions/checkout@v2
    - uses: iamssen/couchdb-github-action@master
      with:
        couchdb-version: ${{ matrix.couchdb }}
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm i
    - run: npm run eslint
    - run: ${{ matrix.command }}
